# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Gym transport bridge for Yi's byte-frozen H Company Sagent recipe.

The policy implementation in ``vendor/sagent`` is intentionally unmodified.
This module supplies only the compatibility needed to run that policy through
Gym's model transport and OSWorld's host-side ``DesktopEnv`` loop:

* verify and load the exact vendor policy, prompt, and Pydantic-2.11.7 schema;
* adapt the prompt's source VM password to the configured OSWorld password;
* route the vendor Chat Completions payload through Gym without changing its
  structured message history or tool projection;
* optionally append a versioned source-fidelity guardrail to the task
  instruction without mutating the frozen vendor prompt or policy source;
* classify infeasible answers, parse failures, and max-step exhaustion using
  the semantics from Yi's ``holotron3_eval`` reproduction.
"""

from __future__ import annotations

import hashlib
import json
import logging
import tempfile
import time
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Callable, Optional

from responses_api_agents.osworld_agent.vendor.sagent import sagent_osworld_agent as vendor


LOG = logging.getLogger("nemo_gym.osworld_agent.sagent_holo3")

_PACKAGE_DIR = Path(__file__).resolve().parent
_VENDOR_PATH = _PACKAGE_DIR / "vendor" / "sagent" / "sagent_osworld_agent.py"
_PROMPT_PATH = _PACKAGE_DIR / "assets" / "sagent" / "osworld-2025-12-30.j2"
_SCHEMA_PATH = _PACKAGE_DIR / "assets" / "sagent" / "structured_note.schema.json"

VENDOR_SHA256 = "faa098e55d11525466cfed4bb8464d8af5b74e8c6f063658e5300be01508eb04"
PROMPT_SHA256 = "eb21708616ef8b67fdbf477b8918b53ccec2291b3a1153bbe858928e10a47222"
SCHEMA_FILE_SHA256 = "3794cee2114851a57b66350c7370d4f93a5402db1afac7015ff813f88ef1673d"
# ``json.dumps(schema)`` under the exact insertion order emitted by
# Pydantic 2.11.7. This serialized form is appended to the system prompt.
SCHEMA_SERIALIZED_SHA256 = "5b158d9d65c00f0a14d77d5a83804e39abd5eb3c0ebd822fad55b95a166a838b"
SOURCE_PASSWORD = "osworld-public-evaluation"
EXPECTED_PASSWORD_OCCURRENCES = 2

SOURCE_FIDELITY_GUARDRAIL_VERSION = "source_fidelity_v2"
SOURCE_FIDELITY_GUARDRAIL = """<source_editing_guardrail version="2">
When editing an existing user-provided source file, make the smallest localized
change needed for the task. Treat the visible cursor position, selection, and
indentation as evidence: if the caret is already after leading whitespace on a
blank or placeholder line, type only the code text and do not duplicate that
whitespace. Preserve existing observable behavior, comments, call sites, and
output format unless the task explicitly requires changing them. Do not
activate commented-out behavior or add labels, headers, prose, or other output
that the task did not request.

After saving, syntax-check or run the artifact before making more edits when
feasible. If validation fails, prefer Undo or one localized correction based on
the observed error, then validate again; do not cascade into speculative
rewrites. Use a whole-file rewrite only when localized recovery is impossible.
Before such a rewrite, inspect and reconstruct the complete original faithfully,
including all functions, call sites, comments, and output, and then apply only
the requested change. Before finishing, inspect both the artifact and its output
and remove any unrequested differences.
</source_editing_guardrail>"""


class SagentAssetIntegrityError(RuntimeError):
    """A checked-in Yi/H Company asset no longer matches its frozen source."""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _verified_bytes(path: Path, expected_sha256: str) -> bytes:
    try:
        data = path.read_bytes()
    except OSError as exc:
        raise SagentAssetIntegrityError(f"Cannot read frozen Sagent asset {path}: {exc}") from exc
    observed = _sha256(data)
    if observed != expected_sha256:
        raise SagentAssetIntegrityError(
            f"Frozen Sagent asset hash mismatch for {path}: expected {expected_sha256}, observed {observed}"
        )
    return data


def load_frozen_schema() -> dict[str, Any]:
    """Load the schema generated by Yi's exact Pydantic 2.11.7 runtime."""

    data = _verified_bytes(_SCHEMA_PATH, SCHEMA_FILE_SHA256)
    try:
        schema = json.loads(data)
    except json.JSONDecodeError as exc:
        raise SagentAssetIntegrityError(f"Frozen Sagent schema is invalid JSON: {exc}") from exc
    if not isinstance(schema, dict):
        raise SagentAssetIntegrityError("Frozen Sagent schema must be a JSON object")
    serialized = json.dumps(schema).encode("utf-8")
    observed = _sha256(serialized)
    if observed != SCHEMA_SERIALIZED_SHA256:
        raise SagentAssetIntegrityError(
            "Frozen Sagent schema insertion order changed: "
            f"expected {SCHEMA_SERIALIZED_SHA256}, observed {observed}"
        )
    return schema


def verify_sagent_assets() -> dict[str, str]:
    """Fail closed if any source artifact differs from Yi's reproduction."""

    _verified_bytes(_VENDOR_PATH, VENDOR_SHA256)
    prompt = _verified_bytes(_PROMPT_PATH, PROMPT_SHA256)
    if prompt.count(SOURCE_PASSWORD.encode("utf-8")) != EXPECTED_PASSWORD_OCCURRENCES:
        raise SagentAssetIntegrityError(
            f"Expected {EXPECTED_PASSWORD_OCCURRENCES} source-password occurrences in {_PROMPT_PATH}"
        )
    load_frozen_schema()
    return {
        "vendor_sha256": VENDOR_SHA256,
        "prompt_sha256": PROMPT_SHA256,
        "schema_file_sha256": SCHEMA_FILE_SHA256,
        "schema_serialized_sha256": SCHEMA_SERIALIZED_SHA256,
    }


class SagentHolo3Agent:
    """Adapt the exact Sagent policy contract to Gym's native-agent runner."""

    def __init__(
        self,
        *,
        platform: str = "ubuntu",
        model: str = "Hcompany/Holotron-3-Nano",
        max_steps: int = 100,
        max_tokens: int = vendor.DEFAULT_MAX_COMPLETION_TOKENS,
        top_p: Optional[float] = 0.95,
        temperature: float = vendor.DEFAULT_TEMPERATURE,
        action_space: str = "pyautogui",
        observation_type: str = "screenshot",
        screen_size: tuple[int, int] = (1920, 1080),
        client_password: str = "password",
        max_image_history_length: int = vendor.DEFAULT_MAX_IMAGES,
        max_time_s: float = vendor.DEFAULT_MAX_TIME_S,
        llm_timeout_s: float = vendor.DEFAULT_LLM_TIMEOUT_S,
        wait_after_s: float = vendor.DEFAULT_WAIT_AFTER_S,
        action_pause_s: float = 0.2,
        cursor_free_observations: bool = True,
        initial_observation_delay_s: float = 10.0,
        evaluation_settle_s: float = 10.0,
        refresh_observation_after_noop: bool = True,
        transport_retries: int = 20,
        transport_retry_sleep_s: float = 5.0,
        enable_thinking: Optional[bool] = None,
        drop_response_format: bool = False,
        preserve_source_fidelity: bool = False,
        log_context: Optional[Mapping[str, Any]] = None,
    ) -> None:
        if platform.lower() != "ubuntu":
            raise ValueError(f"Sagent Holo3 supports only Ubuntu, got {platform!r}")
        if action_space != "pyautogui" or observation_type != "screenshot":
            raise ValueError("Sagent Holo3 requires pyautogui actions and screenshot observations")
        if max_steps < 1 or max_image_history_length < 1:
            raise ValueError("max_steps and max_image_history_length must be positive")
        if transport_retries < 1:
            raise ValueError("transport_retries must be positive")
        if top_p is not None and not 0.0 < top_p <= 1.0:
            raise ValueError("top_p must be in (0, 1]")
        if initial_observation_delay_s < 0 or evaluation_settle_s < 0:
            raise ValueError("initial_observation_delay_s and evaluation_settle_s must be non-negative")

        verify_sagent_assets()
        self.model = model
        self.max_steps = max_steps
        self.top_p = top_p
        self.wait_after_s = float(wait_after_s)
        self.action_pause_s = float(action_pause_s)
        self.cursor_free_observations = bool(cursor_free_observations)
        self.initial_observation_delay_s = float(initial_observation_delay_s)
        self.evaluation_settle_s = float(evaluation_settle_s)
        self.refresh_observation_after_noop = bool(refresh_observation_after_noop)
        self.transport_retries = transport_retries
        self.transport_retry_sleep_s = float(transport_retry_sleep_s)
        self.enable_thinking = enable_thinking
        self.drop_response_format = drop_response_format
        self.preserve_source_fidelity = bool(preserve_source_fidelity)
        self.instruction_guardrail_version = (
            SOURCE_FIDELITY_GUARDRAIL_VERSION if self.preserve_source_fidelity else None
        )
        self.instruction_guardrail_sha256 = (
            _sha256(SOURCE_FIDELITY_GUARDRAIL.encode("utf-8"))
            if self.preserve_source_fidelity
            else None
        )
        self.log_context = dict(log_context or {})
        self.logger = LOG
        self._step_idx = 0
        self._parse_attempt = 0

        source_prompt = _verified_bytes(_PROMPT_PATH, PROMPT_SHA256).decode("utf-8")
        replacement_count = source_prompt.count(SOURCE_PASSWORD)
        effective_prompt = source_prompt.replace(SOURCE_PASSWORD, client_password)
        self.prompt_source_sha256 = PROMPT_SHA256
        self.prompt_effective_sha256 = _sha256(effective_prompt.encode("utf-8"))
        self.prompt_password_replacement_count = replacement_count

        # The exact vendor class accepts only a prompt path. Keep the source
        # template immutable and stage the password-adapted bytes per agent.
        self._prompt_dir = tempfile.TemporaryDirectory(prefix="nemo-gym-sagent-prompt-")
        effective_prompt_path = Path(self._prompt_dir.name) / _PROMPT_PATH.name
        effective_prompt_path.write_text(effective_prompt, encoding="utf-8")

        self._agent = vendor.SagentOSWorldAgent(
            model=model,
            max_steps=max_steps,
            prompt_path=str(effective_prompt_path),
            screen_size=screen_size,
            max_images=max_image_history_length,
            max_time_s=max_time_s,
            temperature=temperature,
            max_completion_tokens=max_tokens,
            llm_timeout_s=llm_timeout_s,
            password=client_password,
        )

        # Pydantic is a dependency of Gym and can move independently. Replace
        # the runtime-generated schema with Yi's exact Pydantic-2.11.7 output,
        # then render the prompt from that frozen object and insertion order.
        self.schema = load_frozen_schema()
        self._agent.output_schema = self.schema
        self._agent.system_prompt = vendor.render_system_prompt(
            prompt_path=effective_prompt_path,
            output_schema=self.schema,
            max_steps=max_steps,
            max_time_s=max_time_s,
            start_time=self._agent.start_time,
            services={"desktop": "RemoteDesktopDriver"},
            password=client_password,
        )
        self._agent._call_llm = self._call_vendor_llm

        # ``run_osworld_task`` replaces this instance attribute with Gym's
        # synchronous model transport after construction.
        self.call_llm: Callable[[dict[str, Any], Optional[str]], Any] = self._unconfigured_call_llm

    @property
    def history(self) -> list[dict[str, Any]]:
        return self._agent.history

    @property
    def system_prompt(self) -> str:
        return self._agent.system_prompt

    def _unconfigured_call_llm(self, _payload: dict[str, Any], _model: Optional[str] = None) -> Any:
        raise RuntimeError("Sagent Holo3 model transport is not configured")

    def reset(self, logger: Optional[logging.Logger] = None, *_args: Any, **_kwargs: Any) -> None:
        self._agent.history.clear()
        self._step_idx = 0
        self._parse_attempt = 0
        if logger is not None:
            self.logger = logger
            self._agent.logger = logger

    def _normalize_message(self, response: Any) -> dict[str, Any]:
        if isinstance(response, str):
            return {"content": response}
        if isinstance(response, Mapping):
            return dict(response)
        if hasattr(response, "model_dump"):
            value = response.model_dump()
            if isinstance(value, dict):
                return value
        return {
            "content": getattr(response, "content", None),
            "reasoning_content": getattr(response, "reasoning_content", None),
        }

    def _call_vendor_llm(self, vendor_payload: dict[str, Any]) -> dict[str, Any]:
        self._parse_attempt += 1
        payload = dict(vendor_payload)
        if self.top_p is not None:
            payload["top_p"] = self.top_p
        if self.enable_thinking is not None:
            payload["chat_template_kwargs"] = {"enable_thinking": self.enable_thinking}
        if self.drop_response_format:
            payload.pop("response_format", None)
        payload["_nemo_gym_return_message"] = True
        payload["_nemo_gym_require_stop"] = True
        payload["_osworld_log_context"] = {
            **self.log_context,
            "step": self._step_idx + 1,
            "parse_attempt": self._parse_attempt,
        }

        last_error = ""
        for transport_attempt in range(1, self.transport_retries + 1):
            try:
                message = self._normalize_message(self.call_llm(payload, self.model))
                if str(message.get("content") or "").strip():
                    return message
                last_error = "empty content"
                self.logger.error(
                    "Sagent model returned empty content (transport attempt %d/%d)",
                    transport_attempt,
                    self.transport_retries,
                )
            except Exception as exc:  # noqa: BLE001 - mirrors H's retry contract.
                last_error = repr(exc)
                self.logger.error(
                    "Sagent model call failed (transport attempt %d/%d): %s",
                    transport_attempt,
                    self.transport_retries,
                    exc,
                )
            if transport_attempt < self.transport_retries:
                time.sleep(self.transport_retry_sleep_s)
        raise RuntimeError(f"API max retries exceeded: {last_error}")

    def predict(self, instruction: str, obs: Mapping[str, Any]) -> tuple[dict[str, Any], list[str], dict[str, Any]]:
        screenshot = obs.get("screenshot")
        if not isinstance(screenshot, (bytes, bytearray)) or not screenshot:
            raise ValueError("Sagent Holo3 requires non-empty screenshot bytes")

        self._parse_attempt = 0
        effective_instruction = instruction
        if self.preserve_source_fidelity:
            effective_instruction = (
                f"{instruction.rstrip()}\n\n{SOURCE_FIDELITY_GUARDRAIL}"
            )

        response, actions, info = self._agent.predict(
            effective_instruction,
            bytes(screenshot),
            self._step_idx,
        )
        self._step_idx += 1
        info = dict(info or {})
        if self.preserve_source_fidelity:
            info["_osworld_instruction_guardrail_version"] = self.instruction_guardrail_version
            info["_osworld_instruction_guardrail_sha256"] = self.instruction_guardrail_sha256
        info["parse_attempt"] = self._parse_attempt
        tool_name = str(info.get("tool_name") or "").strip().lower()

        if actions == ["WAIT"]:
            if tool_name != "update_plan":
                raise RuntimeError(f"Unexpected Sagent WAIT sentinel for tool {tool_name!r}")
            actions = []

        if actions == ["DONE"] and tool_name == vendor.ANSWER_TOOL_NAME:
            content = str((info.get("tool_call") or {}).get("content") or "")
            if vendor.INFEASIBLE_MARKER in content:
                actions = ["FAIL"]
                info["_osworld_outcome"] = "infeasible"
            else:
                info["_osworld_outcome"] = "done"

        if actions == ["FAIL"]:
            action_description = str(info.get("action") or "").lower()
            if tool_name == "parse_error":
                # Yi records this as a valid, deterministic zero rather than
                # stepping FAIL (which could incorrectly award infeasible).
                actions = []
                info["_osworld_force_score_zero"] = True
                info["_osworld_failure_reason"] = "parse_error"
            elif "maximum step limit" in action_description:
                # Evaluate the final desktop without a terminal FAIL action.
                actions = []
                info["_osworld_outcome"] = "max_steps_exhausted"
            elif info.get("_osworld_outcome") != "infeasible":
                actions = []
                info["_osworld_force_score_zero"] = True
                info["_osworld_failure_reason"] = "vendor_fail_without_infeasible_marker"

        if tool_name in vendor.DESKTOP_ACTION_TOOLS:
            info["_osworld_sleep_after_execution"] = self.action_pause_s + self.wait_after_s
        elif tool_name == "wait_desktop":
            # The wait itself happens inside the generated VM command. Yi then
            # applies pyautogui.PAUSE once, just like every other executed tool.
            info["_osworld_sleep_after_execution"] = self.action_pause_s
        else:
            # update_plan has no env.step; terminal actions are stepped without
            # a post-action pause.
            info["_osworld_sleep_after_execution"] = 0.0
        return response, list(actions), info
